export const appColors = {
  light: {
    primary: '#310d6b',
    background: '#F7F7F7',
    overlay: 'rgba(0, 0, 0, 0.5)',
    border: 'darkgray',
    shadow: 'black',
    text: 'black',
    input: '#E0E0E0',
    icon: 'black',
    disabled: 'gray',
    unfocused: 'gray',
  },
  dark: {
    primary: '#5a3e9b',
    background: '#1C1C1C',
    overlay: 'rgba(0, 0, 0, 0.5)',
    border: 'lightgray',
    shadow: 'white',
    text: 'white',
    input: '#2A2A2A',
    icon: 'white',
    disabled: 'gray',
    unfocused: 'gray',
  },
};
