import { StyleSheet } from 'react-native';

import { appColors } from './appColors';

const lightTheme = StyleSheet.create({
  backButton: {
    left: 15,
    position: 'absolute',
    top: 45,
    zIndex: 1,
  },
  bottomTabBar: {
    backgroundColor: appColors.light.background,
    borderTopColor: appColors.light.border,
    borderTopWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 8,
  },
  button: {
    backgroundColor: appColors.light.primary,
    borderRadius: 5,
    marginBottom: 20,
    marginTop: 10,
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  buttonDisabled: {
    backgroundColor: appColors.light.disabled,
    borderRadius: 5,
    marginBottom: 20,
    marginTop: 10,
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  buttonText: {
    color: '#fff' as string,
    fontSize: 20,
  },
  container: {
    alignItems: 'center',
    backgroundColor: appColors.light.background,
    flex: 1,
    justifyContent: 'center',
  },
  containerLeftAligned: {
    alignItems: 'flex-start',
    backgroundColor: appColors.light.background,
    flex: 1,
    justifyContent: 'center',
  },
  filledIconButton: {
    alignItems: 'center',
    backgroundColor: appColors.light.primary,
    borderRadius: 5,
    flex: 1,
    justifyContent: 'center',
    margin: 5,
    padding: 10,
  },
  input: {
    backgroundColor: appColors.light.input,
    borderColor: appColors.light.border,
    borderRadius: 5,
    borderWidth: 1,
    color: appColors.light.text,
    marginBottom: 20,
    padding: 10,
    width: '76%',
  },
  largeInput: {
    backgroundColor: appColors.light.input,
    borderColor: appColors.light.border,
    borderRadius: 5,
    borderWidth: 1,
    color: appColors.light.text,
    height: 100,
    marginBottom: 20,
    padding: 10,
    width: '76%',
  },
  loadingOverlay: {
    alignItems: 'center',
    backgroundColor: appColors.light.overlay,
    bottom: 0,
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 1000,
  },
  text: {
    color: appColors.light.text,
    textAlign: 'left',
  },
  textBold: {
    color: appColors.light.text,
    fontWeight: 'bold',
    textAlign: 'left',
  },
  titleText: {
    alignItems: 'center',
    color: appColors.light.text,
    fontSize: 26,
    justifyContent: 'center',
    position: 'absolute',
    top: 45,
    zIndex: 1,
  },
  topRow: {
    flexDirection: 'row',
    position: 'absolute',
    right: 15,
    top: 45,
    zIndex: 1,
  },
});

const darkTheme = StyleSheet.create({
  backButton: {
    left: 15,
    position: 'absolute',
    top: 45,
    zIndex: 1,
  },
  bottomTabBar: {
    backgroundColor: appColors.dark.background,
    borderTopColor: appColors.dark.border,
    borderTopWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 8,
  },
  button: {
    backgroundColor: appColors.dark.primary,
    borderRadius: 5,
    marginBottom: 20,
    marginTop: 10,
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  buttonDisabled: {
    backgroundColor: appColors.dark.disabled,
    borderRadius: 5,
    marginBottom: 20,
    marginTop: 10,
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  buttonText: {
    color: '#fff' as string,
    fontSize: 20,
  },
  container: {
    alignItems: 'center',
    backgroundColor: appColors.dark.background,
    flex: 1,
    justifyContent: 'center',
  },
  containerLeftAligned: {
    alignItems: 'flex-start',
    backgroundColor: appColors.dark.background,
    flex: 1,
    justifyContent: 'center',
  },
  filledIconButton: {
    alignItems: 'center',
    backgroundColor: appColors.dark.primary,
    borderRadius: 5,
    flex: 1,
    justifyContent: 'center',
    margin: 5,
    padding: 10,
  },
  input: {
    backgroundColor: appColors.dark.input,
    borderColor: appColors.dark.border,
    borderRadius: 5,
    borderWidth: 1,
    color: appColors.dark.text,
    marginBottom: 20,
    padding: 10,
    width: '76%',
  },
  largeInput: {
    backgroundColor: appColors.dark.input,
    borderColor: appColors.dark.border,
    borderRadius: 5,
    borderWidth: 1,
    color: appColors.dark.text,
    height: 100,
    marginBottom: 20,
    padding: 10,
    width: '76%',
  },
  loadingOverlay: {
    alignItems: 'center',
    backgroundColor: appColors.dark.overlay,
    bottom: 0,
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 1000,
  },
  text: {
    color: appColors.dark.text,
    textAlign: 'left',
  },
  textBold: {
    color: appColors.dark.text,
    fontWeight: 'bold',
    textAlign: 'left',
  },
  titleText: {
    alignItems: 'center',
    color: appColors.dark.text,
    fontSize: 26,
    justifyContent: 'center',
    position: 'absolute',
    top: 45,
    zIndex: 1,
  },
  topRow: {
    flexDirection: 'row',
    position: 'absolute',
    right: 15,
    top: 45,
    zIndex: 1,
  },
});

export { darkTheme, lightTheme };
