import { StyleSheet } from 'react-native';

const lightTheme = StyleSheet.create({
  bottomTabBar: {
    backgroundColor: '#F7F7F7' as string,
    borderTopColor: 'darkgray' as string,
    borderTopWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 8,
  },
  button: {
    backgroundColor: '#310d6b' as string,
    borderRadius: 5,
    marginBottom: 20,
    marginTop: 10,
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  buttonDisabled: {
    backgroundColor: 'gray' as string,
    borderRadius: 5,
    marginBottom: 20,
    marginTop: 10,
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  buttonText: {
    color: '#fff' as string,
    fontSize: 20,
  },
  container: {
    alignItems: 'center',
    backgroundColor: '#F7F7F7' as string,
    flex: 1,
    justifyContent: 'center',
    padding: 20,
  },
  filledIconButton: {
    alignItems: 'center',
    backgroundColor: '#310d6b' as string,
    borderRadius: 5,
    flex: 1,
    justifyContent: 'center',
    margin: 5,
    padding: 10,
  },
  input: {
    backgroundColor: '#E0E0E0' as string,
    borderColor: 'darkgray' as string,
    borderRadius: 5,
    borderWidth: 1,
    color: 'black' as string,
    marginBottom: 20,
    padding: 10,
    width: '85%',
  },

  largeInput: {
    backgroundColor: '#E0E0E0' as string,
    borderColor: 'darkgray' as string,
    borderRadius: 5,
    borderWidth: 1,
    color: 'black' as string,
    height: 100,
    marginBottom: 20,
    padding: 10,
    width: '85%',
  },
  loadingOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)' as string,
    bottom: 0,
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 1000,
  },
  text: {
    color: 'black' as string,
  },
  titleText: {
    alignItems: 'center',
    color: 'black' as string,
    fontSize: 26,
    justifyContent: 'center',
    position: 'absolute',
    top: 35,
    zIndex: 1,
  },
});

const darkTheme = StyleSheet.create({
  bottomTabBar: {
    backgroundColor: '#1C1C1C' as string,
    borderTopColor: 'lightgray' as string,
    borderTopWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 8,
  },
  button: {
    backgroundColor: '#5a3e9b' as string,
    borderRadius: 5,
    marginBottom: 20,
    marginTop: 10,
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  buttonDisabled: {
    backgroundColor: 'gray' as string,
    borderRadius: 5,
    marginBottom: 20,
    marginTop: 10,
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  buttonText: {
    color: '#fff' as string,
    fontSize: 20,
  },
  container: {
    alignItems: 'center',
    backgroundColor: '#1C1C1C' as string,
    flex: 1,
    justifyContent: 'center',
    padding: 20,
  },
  filledIconButton: {
    alignItems: 'center',
    backgroundColor: '#5a3e9b' as string,
    borderRadius: 5,
    flex: 1,
    justifyContent: 'center',
    margin: 5,
    padding: 10,
  },
  input: {
    backgroundColor: '#2A2A2A' as string,
    borderColor: 'lightgray' as string,
    borderRadius: 5,
    borderWidth: 1,
    color: 'white' as string,
    marginBottom: 20,
    padding: 10,
    width: '85%',
  },
  largeInput: {
    backgroundColor: '#2A2A2A' as string,
    borderColor: 'lightgray' as string,
    borderRadius: 5,
    borderWidth: 1,
    color: 'white' as string,
    height: 100,
    marginBottom: 20,
    padding: 10,
    width: '85%',
  },
  loadingOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)' as string,
    bottom: 0,
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 1000,
  },
  text: {
    color: 'white' as string,
  },
  titleText: {
    alignItems: 'center',
    color: 'white' as string,
    fontSize: 26,
    justifyContent: 'center',
    position: 'absolute',
    top: 35,
    zIndex: 1,
  },
});

export { darkTheme, lightTheme };
